
server:
  port: 8700

spring:
  application:
    name: neusoftgatewayzuul
    

eureka:
  instance:
    prefer-ip-address: true   #以IP注册为主， 不以主机名注册微服务
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/  
    register-with-eureka: false
    
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

  
  